EXPENDABLES = scpdsi
LFLAGS = -mno-cygwin

scpdsi: scpdsi.cpp 
	g++ $(LFLAGS) -O scpdsi.cpp -g -o scpdsi

clean:
	rm -f $(EXPENDABLES)
	g++ $(LFLAGS) -O scpdsi.cpp -g -o scpdsi

all:
	rm -f $(EXPENDABLES)
	g++ $(LFLAGS) -O scpdsi.cpp -g -o scpdsi
